require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShowcasesController do

  # This should return the minimal set of attributes required to create a valid
  # Showcase. As you add validations to Showcase, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShowcasesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all showcases as @showcases" do
      showcase = Showcase.create! valid_attributes
      get :index, {}, valid_session
      assigns(:showcases).should eq([showcase])
    end
  end

  describe "GET show" do
    it "assigns the requested showcase as @showcase" do
      showcase = Showcase.create! valid_attributes
      get :show, {:id => showcase.to_param}, valid_session
      assigns(:showcase).should eq(showcase)
    end
  end

  describe "GET new" do
    it "assigns a new showcase as @showcase" do
      get :new, {}, valid_session
      assigns(:showcase).should be_a_new(Showcase)
    end
  end

  describe "GET edit" do
    it "assigns the requested showcase as @showcase" do
      showcase = Showcase.create! valid_attributes
      get :edit, {:id => showcase.to_param}, valid_session
      assigns(:showcase).should eq(showcase)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Showcase" do
        expect {
          post :create, {:showcase => valid_attributes}, valid_session
        }.to change(Showcase, :count).by(1)
      end

      it "assigns a newly created showcase as @showcase" do
        post :create, {:showcase => valid_attributes}, valid_session
        assigns(:showcase).should be_a(Showcase)
        assigns(:showcase).should be_persisted
      end

      it "redirects to the created showcase" do
        post :create, {:showcase => valid_attributes}, valid_session
        response.should redirect_to(Showcase.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved showcase as @showcase" do
        # Trigger the behavior that occurs when invalid params are submitted
        Showcase.any_instance.stub(:save).and_return(false)
        post :create, {:showcase => {}}, valid_session
        assigns(:showcase).should be_a_new(Showcase)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Showcase.any_instance.stub(:save).and_return(false)
        post :create, {:showcase => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested showcase" do
        showcase = Showcase.create! valid_attributes
        # Assuming there are no other showcases in the database, this
        # specifies that the Showcase created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Showcase.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => showcase.to_param, :showcase => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested showcase as @showcase" do
        showcase = Showcase.create! valid_attributes
        put :update, {:id => showcase.to_param, :showcase => valid_attributes}, valid_session
        assigns(:showcase).should eq(showcase)
      end

      it "redirects to the showcase" do
        showcase = Showcase.create! valid_attributes
        put :update, {:id => showcase.to_param, :showcase => valid_attributes}, valid_session
        response.should redirect_to(showcase)
      end
    end

    describe "with invalid params" do
      it "assigns the showcase as @showcase" do
        showcase = Showcase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Showcase.any_instance.stub(:save).and_return(false)
        put :update, {:id => showcase.to_param, :showcase => {}}, valid_session
        assigns(:showcase).should eq(showcase)
      end

      it "re-renders the 'edit' template" do
        showcase = Showcase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Showcase.any_instance.stub(:save).and_return(false)
        put :update, {:id => showcase.to_param, :showcase => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested showcase" do
      showcase = Showcase.create! valid_attributes
      expect {
        delete :destroy, {:id => showcase.to_param}, valid_session
      }.to change(Showcase, :count).by(-1)
    end

    it "redirects to the showcases list" do
      showcase = Showcase.create! valid_attributes
      delete :destroy, {:id => showcase.to_param}, valid_session
      response.should redirect_to(showcases_url)
    end
  end

end
